language: node_js
node_js:
- node
- 6
- 5
- 4
- 4.0.0
sudo: false
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_73ea1dbf79ec_key -iv $encrypted_73ea1dbf79ec_iv
  -in .env.enc -out .env -d
install:
- yarn --production
- yarn add --dev babel-register
